#!/bin/bash

# the name of your job showing on the queue system
#BSUB -J tytellmusc
#BSUB -q normal_public6

# the system output and error message output, %J will show as your jobID
#BSUB -o test_muscle_mass.stdout
#BSUB -e test_muscle_mass.err

#BSUB -u eric.tytell@tufts.edu
#BSUB -N

#enter your working directory
cd ~etytel01/Matlab/muscle

# Finally, Start the program
matlab -nodisplay < run_test_muscle_mass.m > test_muscle_mass.out